name: Auto Merge

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge Dependabot PRs
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          command: 'merge'
          target: 'minor'
