name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20-bullseye-slim
    env:
      NODE_ENV: test
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres

    services:
      postgres:
        image: postgres:16.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install PostgreSQL client
        run: apt-get update & apt-get install -y postgresql-client
      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432; do sleep 2; done
      - name: Execute initial SQL file
        run: PGPASSWORD=postgres psql -h localhost -U postgres -d platform -a -f ./init-db.sql
      - name: Install dependencies
        run: yarn install --no-cache
      - name: Install Nest CLI
        run: npm i -g @nestjs/cli
      - name: Generate the prisma client
        run: yarn run generate
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
      - name: Run migrations
        run: yarn run migrate:test
      - name: Run tests
        run: yarn run test
      - run: echo "🚀 This job's status is ${{ job.status }}."
